[package]
name = "block-wasm"
version = "0.1.0"
edition = "2021"
authors = ["hrloca<hr.loca@gmail.com>"]
description = "block-wasm"
license = "MIT/Apache-2.0"
repository = "https://github.com/hrloca/block-wasm"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
